# Generated by Django 3.1.1 on 2020-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20201010_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rank',
            field=models.CharField(default='Friend', max_length=100),
            preserve_default=False,
        ),
    ]
