# Generated by Django 3.1.1 on 2020-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
